openapi: 3.0.0
info:
  title: CheckList API
  version: 1.0.0
paths:
  /selectedItems:
    get:
      summary: Get selected items
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    title:
                      type: string
                    description:
                      type: string

    post:
      summary: Add selected items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
      responses:
        '200':
          description: OK

    put:
      summary: Update selected items
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  description:
                    type: string
      responses:
        '200':
          description: OK

  /selectedItems/{id}:
    put:
      summary: Remove selected item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
